ALTER TABLE assistant_runtime_tool_mutations
    ADD COLUMN IF NOT EXISTS request_hash CHAR(64) NULL AFTER event_key;

CREATE TABLE IF NOT EXISTS aporia_effect_contracts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    contract_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    episode_ref CHAR(64) NOT NULL,
    operation_id CHAR(64) NOT NULL,
    action_name VARCHAR(80) NOT NULL,
    action_commitment CHAR(64) NOT NULL,
    mode VARCHAR(24) NOT NULL,
    domain_name VARCHAR(80) NOT NULL,
    operation_name VARCHAR(80) NOT NULL,
    resource_commitment CHAR(64) NOT NULL,
    effect_commitment CHAR(64) NOT NULL,
    meet_commitment CHAR(64) NOT NULL,
    decision VARCHAR(32) NOT NULL,
    allowed TINYINT(1) NOT NULL,
    reversible TINYINT(1) NOT NULL,
    external_effect TINYINT(1) NOT NULL,
    idempotent TINYINT(1) NOT NULL,
    approval_required TINYINT(1) NOT NULL,
    guarded_eligible TINYINT(1) NOT NULL,
    compensation VARCHAR(80) NULL,
    risk DECIMAL(6,5) NOT NULL,
    cost_units DECIMAL(12,4) NOT NULL,
    preconditions_json JSON NOT NULL,
    postconditions_json JSON NOT NULL,
    reason_codes_json JSON NOT NULL,
    authority_commitment CHAR(64) NOT NULL,
    idempotency_key_commitment CHAR(64) NULL,
    policy_version CHAR(64) NOT NULL,
    approval_basis VARCHAR(80) NOT NULL,
    evidence_refs_json JSON NOT NULL,
    causal_parent_ids_json JSON NOT NULL,
    maximum_scope_json JSON NOT NULL,
    event_name VARCHAR(160) NOT NULL,
    event_version INT UNSIGNED NOT NULL,
    environment VARCHAR(24) NOT NULL,
    stream VARCHAR(24) NOT NULL,
    category VARCHAR(24) NOT NULL,
    component VARCHAR(80) NOT NULL,
    actor_type VARCHAR(24) NOT NULL,
    lifecycle_phase VARCHAR(24) NOT NULL,
    outcome VARCHAR(24) NOT NULL,
    reason_code VARCHAR(80) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_aporia_effect_contract_id (tenant_id, contract_id),
    UNIQUE KEY uq_aporia_effect_contract_operation (tenant_id, operation_id),
    KEY idx_aporia_effect_contract_mode_created (tenant_id, mode, created_at),
    KEY idx_aporia_effect_contract_decision_created (tenant_id, decision, created_at),
    CONSTRAINT chk_aporia_effect_contract_mode CHECK (mode IN ('shadow','advisory','guarded_reversible')),
    CONSTRAINT chk_aporia_effect_contract_decision CHECK (decision IN ('shadow_observed','advisory_only','safe_prefix_allowed','blocked','evidence_required','escalation_required')),
    CONSTRAINT chk_aporia_effect_contract_risk CHECK (risk >= 0 AND risk <= 1),
    CONSTRAINT chk_aporia_effect_contract_audit CHECK (event_name = 'aporia.hirt.product.effect_contract.recorded' AND event_version = 1 AND stream = 'system' AND category = 'audit' AND component = 'aporia-product-hirt-gateway' AND actor_type = 'worker' AND lifecycle_phase IN ('succeeded','rejected') AND outcome IN ('succeeded','rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS aporia_effect_outcomes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    outcome_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    operation_id CHAR(64) NOT NULL,
    state VARCHAR(24) NOT NULL,
    result_commitment CHAR(64) NOT NULL,
    reason_code VARCHAR(80) NOT NULL,
    event_name VARCHAR(160) NOT NULL,
    event_version INT UNSIGNED NOT NULL,
    environment VARCHAR(24) NOT NULL,
    stream VARCHAR(24) NOT NULL,
    category VARCHAR(24) NOT NULL,
    component VARCHAR(80) NOT NULL,
    actor_type VARCHAR(24) NOT NULL,
    action_name VARCHAR(80) NOT NULL,
    lifecycle_phase VARCHAR(24) NOT NULL,
    outcome VARCHAR(24) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_aporia_effect_outcome_id (tenant_id, outcome_id),
    UNIQUE KEY uq_aporia_effect_outcome_operation (tenant_id, operation_id),
    KEY idx_aporia_effect_outcome_state_created (tenant_id, state, created_at),
    CONSTRAINT fk_aporia_effect_outcome_contract FOREIGN KEY (tenant_id, operation_id) REFERENCES aporia_effect_contracts (tenant_id, operation_id) ON DELETE CASCADE,
    CONSTRAINT chk_aporia_effect_outcome_state CHECK (state IN ('executed','compensated','failed')),
    CONSTRAINT chk_aporia_effect_outcome_audit CHECK (event_name = 'aporia.hirt.product.effect_outcome.recorded' AND event_version = 1 AND stream = 'system' AND category = 'audit' AND component = 'aporia-product-hirt-gateway' AND actor_type = 'worker' AND action_name = 'verify_effect_outcome' AND lifecycle_phase IN ('succeeded','failed') AND outcome IN ('succeeded','failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
