CREATE TABLE IF NOT EXISTS `aporia_lacuna_outbox` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `source_event_id` bigint unsigned NOT NULL,
  `envelope_id` char(36) NOT NULL,
  `algorithm_version` int unsigned NOT NULL,
  `delivery_key` char(64) NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'pending',
  `fencing_token` bigint unsigned NOT NULL DEFAULT 0,
  `owner_token_hash` char(64) DEFAULT NULL,
  `attempts` int unsigned NOT NULL DEFAULT 0,
  `lease_expires_at` datetime(6) DEFAULT NULL,
  `next_attempt_at` datetime(6) DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `reason_code` varchar(80) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_lacuna_outbox_delivery` (`delivery_key`),
  UNIQUE KEY `uniq_aporia_lacuna_outbox_source` (`tenant_id`, `source_event_id`, `algorithm_version`),
  UNIQUE KEY `uniq_aporia_lacuna_outbox_envelope` (`tenant_id`, `envelope_id`, `algorithm_version`),
  KEY `idx_aporia_lacuna_outbox_pending` (`status`, `next_attempt_at`, `id`),
  CONSTRAINT `fk_aporia_lacuna_outbox_event` FOREIGN KEY (`tenant_id`, `source_event_id`) REFERENCES `aporia_events` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_lacuna_outbox_status` CHECK (`status` IN ('pending','leased','completed','rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_lacuna_runs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `run_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `source_event_id` bigint unsigned NOT NULL,
  `envelope_id` char(36) NOT NULL,
  `algorithm_version` int unsigned NOT NULL,
  `feature_space_version` int unsigned NOT NULL,
  `policy_hash` char(64) NOT NULL,
  `input_commitment` char(64) NOT NULL,
  `control_seed` char(64) NOT NULL,
  `execution_status` varchar(24) NOT NULL,
  `interpretation_status` varchar(24) NOT NULL,
  `reason_codes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`reason_codes_json`)),
  `completed_at` datetime(6) DEFAULT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_lacuna_run_id` (`run_id`),
  UNIQUE KEY `uniq_aporia_lacuna_run_source` (`tenant_id`, `source_event_id`, `algorithm_version`),
  UNIQUE KEY `uniq_aporia_lacuna_run_tenant_id` (`tenant_id`, `id`),
  KEY `idx_aporia_lacuna_run_tenant` (`tenant_id`, `completed_at`, `id`),
  CONSTRAINT `fk_aporia_lacuna_run_event` FOREIGN KEY (`tenant_id`, `source_event_id`) REFERENCES `aporia_events` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_lacuna_run_execution` CHECK (`execution_status` IN ('completed','rejected')),
  CONSTRAINT `chk_aporia_lacuna_run_interpretation` CHECK (`interpretation_status` IN ('observed','unknown','not_evaluable'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_lacuna_branches` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `branch_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `run_id` bigint unsigned NOT NULL,
  `branch_name` varchar(40) NOT NULL,
  `control_kind` varchar(24) NOT NULL,
  `instrument_order_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`instrument_order_json`)),
  `capability_hash` char(64) NOT NULL,
  `capability_status` varchar(24) NOT NULL,
  `input_commitment` char(64) NOT NULL,
  `output_commitment` char(64) NOT NULL,
  `changed_dimensions` int unsigned NOT NULL,
  `targeted_dimensions` int unsigned NOT NULL,
  `operation_index` int unsigned NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_lacuna_branch_id` (`branch_id`),
  UNIQUE KEY `uniq_aporia_lacuna_branch_name` (`tenant_id`, `run_id`, `branch_name`),
  UNIQUE KEY `uniq_aporia_lacuna_branch_operation` (`tenant_id`, `run_id`, `operation_index`),
  CONSTRAINT `fk_aporia_lacuna_branch_run` FOREIGN KEY (`tenant_id`, `run_id`) REFERENCES `aporia_lacuna_runs` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_lacuna_branch_control` CHECK (`control_kind` IN ('lacuna','keep','destroy','random','passive','order_only')),
  CONSTRAINT `chk_aporia_lacuna_capability_status` CHECK (`capability_status` IN ('ready','consumed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_lacuna_measurements` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `run_id` bigint unsigned NOT NULL,
  `metric_name` varchar(64) NOT NULL,
  `metric_version` int unsigned NOT NULL,
  `numeric_value` decimal(20,12) DEFAULT NULL,
  `unit` varchar(32) NOT NULL,
  `evaluability` varchar(24) NOT NULL,
  `reason_codes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`reason_codes_json`)),
  `baseline_branch_ids_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`baseline_branch_ids_json`)),
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_lacuna_measurement` (`tenant_id`, `run_id`, `metric_name`, `metric_version`),
  CONSTRAINT `fk_aporia_lacuna_measurement_run` FOREIGN KEY (`tenant_id`, `run_id`) REFERENCES `aporia_lacuna_runs` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_lacuna_measurement_eval` CHECK (`evaluability` IN ('observed','unknown','not_evaluable'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
