CREATE TABLE IF NOT EXISTS `aporia_real_pilot_feedback_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `feedback_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `assignment_id` char(36) NOT NULL,
  `episode_ref` char(64) NOT NULL,
  `feedback_correct` tinyint(1) NOT NULL,
  `source` varchar(24) NOT NULL,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_real_pilot_feedback` (`tenant_id`, `feedback_id`),
  UNIQUE KEY `uniq_aporia_real_pilot_episode` (`tenant_id`, `episode_ref`),
  UNIQUE KEY `uniq_aporia_real_pilot_operation` (`tenant_id`, `operation_id`),
  CONSTRAINT `fk_aporia_real_pilot_assignment` FOREIGN KEY (`tenant_id`, `assignment_id`) REFERENCES `aporia_experiment_assignments` (`tenant_id`, `assignment_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_real_pilot_feedback` CHECK (`feedback_correct` IN (0,1) AND `source` = 'sync_user'),
  CONSTRAINT `chk_aporia_real_pilot_audit` CHECK (`event_name` = 'aporia.real_pilot.feedback.recorded' AND `event_version` = 1 AND `stream` = 'user' AND `category` = 'audit' AND `component` = 'aporia-real-pilot' AND `actor_type` = 'user' AND `action_name` = 'record_feedback' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
