CREATE TABLE IF NOT EXISTS `aporia_empirical_runs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `run_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `protocol_key` varchar(64) NOT NULL,
  `protocol_commitment` char(64) NOT NULL,
  `result_commitment` char(64) DEFAULT NULL,
  `status` varchar(24) NOT NULL,
  `operator_user_id` bigint NOT NULL,
  `task_count` int unsigned NOT NULL,
  `arm_count` int unsigned NOT NULL,
  `model_count` int unsigned NOT NULL,
  `observation_count` int unsigned NOT NULL DEFAULT 0,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `started_at` datetime(6) NOT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_empirical_run` (`tenant_id`, `run_id`),
  UNIQUE KEY `uniq_aporia_empirical_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_empirical_status` (`status`, `created_at`, `id`),
  CONSTRAINT `chk_aporia_empirical_run_status` CHECK (`status` IN ('prepared','completed','failed')),
  CONSTRAINT `chk_aporia_empirical_run_shape` CHECK (`task_count` >= 8 AND `arm_count` = 6 AND `model_count` = 2),
  CONSTRAINT `chk_aporia_empirical_run_terminal` CHECK ((`status` = 'prepared' AND `result_commitment` IS NULL AND `completed_at` IS NULL AND `observation_count` = 0) OR (`status` IN ('completed','failed') AND `result_commitment` REGEXP '^[0-9a-f]{64}$' AND `completed_at` IS NOT NULL)),
  CONSTRAINT `chk_aporia_empirical_run_audit` CHECK (`event_name` = 'aporia.experiment.empirical.run' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-empirical-study' AND `actor_type` = 'admin' AND `action_name` = 'execute_empirical_experiment' AND `lifecycle_phase` IN ('accepted','succeeded','failed') AND `outcome` IN ('accepted','succeeded','failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_empirical_observations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `observation_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `run_id` char(36) NOT NULL,
  `task_ref` char(64) NOT NULL,
  `task_commitment` char(64) NOT NULL,
  `pair_ref` char(64) NOT NULL,
  `task_kind` varchar(40) NOT NULL,
  `arm` char(2) NOT NULL,
  `model_name` varchar(80) NOT NULL,
  `seed` bigint unsigned NOT NULL,
  `decision_label` char(1) NOT NULL,
  `decision_commitment` char(64) NOT NULL,
  `expected_label` char(1) NOT NULL,
  `correct` tinyint(1) NOT NULL,
  `confidence` decimal(8,7) NOT NULL,
  `brier_score` decimal(20,12) NOT NULL,
  `calibration_error` decimal(20,12) NOT NULL,
  `critical_regression` tinyint(1) NOT NULL,
  `input_tokens` bigint unsigned NOT NULL,
  `output_tokens` bigint unsigned NOT NULL,
  `total_tokens` bigint unsigned NOT NULL,
  `latency_ms` bigint unsigned NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_empirical_observation` (`tenant_id`, `observation_id`),
  UNIQUE KEY `uniq_aporia_empirical_cell` (`tenant_id`, `run_id`, `task_ref`, `arm`, `model_name`),
  KEY `idx_aporia_empirical_pair` (`tenant_id`, `run_id`, `pair_ref`, `arm`),
  CONSTRAINT `fk_aporia_empirical_observation_run` FOREIGN KEY (`tenant_id`, `run_id`) REFERENCES `aporia_empirical_runs` (`tenant_id`, `run_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_empirical_task_kind` CHECK (`task_kind` IN ('path','negative_autobiography','hirt','factual_consistency','obstruction')),
  CONSTRAINT `chk_aporia_empirical_arm` CHECK (`arm` IN ('C0','C1','C2','C3','C4','C5')),
  CONSTRAINT `chk_aporia_empirical_model` CHECK (`model_name` IN ('gpt-5.6-luna','gpt-5.6-terra')),
  CONSTRAINT `chk_aporia_empirical_labels` CHECK (`decision_label` IN ('A','B') AND `expected_label` IN ('A','B')),
  CONSTRAINT `chk_aporia_empirical_scores` CHECK (`confidence` >= 0 AND `confidence` <= 1 AND `brier_score` >= 0 AND `brier_score` <= 1 AND `calibration_error` >= 0 AND `calibration_error` <= 1),
  CONSTRAINT `chk_aporia_empirical_tokens` CHECK (`total_tokens` = `input_tokens` + `output_tokens`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_empirical_evaluations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `evaluation_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `run_id` char(36) NOT NULL,
  `hypothesis_key` varchar(96) NOT NULL,
  `metric_name` varchar(64) NOT NULL,
  `control_arm` char(2) NOT NULL,
  `treatment_arm` char(2) NOT NULL,
  `sample_size` int unsigned NOT NULL,
  `control_mean` decimal(20,12) NOT NULL,
  `treatment_mean` decimal(20,12) NOT NULL,
  `absolute_effect` decimal(20,12) NOT NULL,
  `relative_effect` decimal(20,12) DEFAULT NULL,
  `confidence_low` decimal(20,12) NOT NULL,
  `confidence_high` decimal(20,12) NOT NULL,
  `verdict` varchar(24) NOT NULL,
  `negative_result` tinyint(1) NOT NULL,
  `reason_codes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`reason_codes_json`)),
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_empirical_evaluation` (`tenant_id`, `evaluation_id`),
  UNIQUE KEY `uniq_aporia_empirical_hypothesis` (`tenant_id`, `run_id`, `hypothesis_key`),
  CONSTRAINT `fk_aporia_empirical_evaluation_run` FOREIGN KEY (`tenant_id`, `run_id`) REFERENCES `aporia_empirical_runs` (`tenant_id`, `run_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_empirical_hypothesis` CHECK (`hypothesis_key` IN ('lacuna_path_dependence_exceeds_passive','path_dependence_not_explained_by_noise','negative_autobiography_improves_continuity','identity_survives_model_transplant','localized_reflexive_obstruction_survives_transport_correction','hirt_reduces_incorrect_effects_without_excessive_blocking','factual_consistency_survives_reflexive_nonclosure')),
  CONSTRAINT `chk_aporia_empirical_metric` CHECK (`metric_name` IN ('path_dependence','identity_continuity','obstruction_localization','hirt_utility','factual_consistency')),
  CONSTRAINT `chk_aporia_empirical_contrast` CHECK (`control_arm` IN ('C0','C1','C2','C3','C4') AND `treatment_arm` IN ('C1','C2','C3','C4','C5') AND `control_arm` <> `treatment_arm`),
  CONSTRAINT `chk_aporia_empirical_verdict` CHECK (`verdict` IN ('supported','falsified','inconclusive')),
  CONSTRAINT `chk_aporia_empirical_interval` CHECK (`sample_size` >= 8 AND `confidence_low` <= `confidence_high`),
  CONSTRAINT `chk_aporia_empirical_reasons` CHECK (json_type(`reason_codes_json`) = 'ARRAY')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
