CREATE TABLE IF NOT EXISTS aporia_product_state_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    state_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    entity_id VARCHAR(191) NOT NULL,
    state_type VARCHAR(40) NOT NULL,
    value_json JSON NOT NULL,
    value_commitment CHAR(64) NOT NULL,
    source_ref VARCHAR(191) NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    observed_at DATETIME(6) NOT NULL,
    valid_from DATETIME(6) NOT NULL,
    valid_until DATETIME(6) NOT NULL,
    confidence DECIMAL(6,5) NOT NULL,
    provenance_json JSON NOT NULL,
    causal_parent_ids_json JSON NOT NULL,
    ontology_version CHAR(64) NOT NULL,
    policy_version CHAR(64) NOT NULL,
    schema_version INT UNSIGNED NOT NULL,
    created_by VARCHAR(80) NOT NULL,
    verified TINYINT(1) NOT NULL,
    authority_rank SMALLINT UNSIGNED NOT NULL,
    freshness_half_life_seconds INT UNSIGNED NOT NULL,
    revision BIGINT UNSIGNED NOT NULL,
    status VARCHAR(24) NOT NULL,
    reason_code VARCHAR(80) NOT NULL,
    supersedes_state_id CHAR(36) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_aporia_product_state_id (tenant_id, state_id),
    UNIQUE KEY uq_aporia_product_state_revision (tenant_id, entity_id, state_type, revision),
    KEY idx_aporia_product_state_current (tenant_id, status, valid_until, authority_rank),
    KEY idx_aporia_product_state_entity (tenant_id, entity_id, state_type, status),
    CONSTRAINT chk_aporia_product_state_type CHECK (state_type IN ('confirmed_fact','derived_belief','hypothesis','prediction','commitment','limitation','negative_outcome','contradiction','uncertainty','outcome','causal_relation','autobiographical_memory','lacuna_state')),
    CONSTRAINT chk_aporia_product_state_source CHECK (source_type IN ('backend_fact','verified_outcome','authorized_external','aporia_inference','model_hypothesis','synthetic_fixture')),
    CONSTRAINT chk_aporia_product_state_confidence CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT chk_aporia_product_state_status CHECK (status IN ('active','superseded','invalidated','rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS aporia_product_state_snapshots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    snapshot_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    source_event_ref VARCHAR(191) NOT NULL,
    state_revision BIGINT UNSIGNED NOT NULL,
    envelope_json JSON NOT NULL,
    candidate_count INT UNSIGNED NOT NULL,
    selected_count INT UNSIGNED NOT NULL,
    excluded_count INT UNSIGNED NOT NULL,
    rejected_count INT UNSIGNED NOT NULL,
    policy_version CHAR(64) NOT NULL,
    schema_version INT UNSIGNED NOT NULL,
    valid_until DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_aporia_product_snapshot_id (tenant_id, snapshot_id),
    UNIQUE KEY uq_aporia_product_snapshot_event (tenant_id, source_event_ref),
    KEY idx_aporia_product_snapshot_latest (tenant_id, state_revision, valid_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS aporia_product_context_exposures (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    exposure_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    turn_ref CHAR(64) NOT NULL,
    snapshot_id CHAR(36) NOT NULL,
    state_revision BIGINT UNSIGNED NOT NULL,
    mode VARCHAR(24) NOT NULL,
    envelope_commitment CHAR(64) NOT NULL,
    receipt_signature CHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_aporia_product_exposure_id (tenant_id, exposure_id),
    UNIQUE KEY uq_aporia_product_exposure_turn (tenant_id, turn_ref),
    KEY idx_aporia_product_exposure_snapshot (tenant_id, snapshot_id),
    CONSTRAINT chk_aporia_product_exposure_mode CHECK (mode IN ('advisory','guarded_reversible'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS aporia_product_runtime_outcomes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    outcome_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    exposure_id CHAR(36) NOT NULL,
    decision_commitment CHAR(64) NOT NULL,
    helpful TINYINT(1) NULL,
    latency_ms INT UNSIGNED NOT NULL,
    cost_units DECIMAL(12,4) NOT NULL,
    critical_regression TINYINT(1) NOT NULL,
    evaluability VARCHAR(24) NOT NULL,
    reason_codes_json JSON NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_aporia_product_outcome_id (tenant_id, outcome_id),
    UNIQUE KEY uq_aporia_product_outcome_exposure (tenant_id, exposure_id),
    CONSTRAINT fk_aporia_product_outcome_exposure FOREIGN KEY (tenant_id, exposure_id) REFERENCES aporia_product_context_exposures (tenant_id, exposure_id) ON DELETE CASCADE,
    CONSTRAINT chk_aporia_product_outcome_eval CHECK (evaluability IN ('not_evaluable','observed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS aporia_product_lacuna_one_shots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    one_shot_id CHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    session_binding CHAR(64) NOT NULL,
    turn_binding CHAR(64) NOT NULL,
    instrument VARCHAR(48) NOT NULL,
    capability_hash CHAR(64) NOT NULL,
    nonce_base64 VARCHAR(64) NOT NULL,
    ciphertext_base64 TEXT NOT NULL,
    input_commitment CHAR(64) NOT NULL,
    output_commitment CHAR(64) NULL,
    destruction_receipt CHAR(64) NULL,
    schema_version INT UNSIGNED NOT NULL,
    status VARCHAR(24) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    consumed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_aporia_product_lacuna_id (tenant_id, one_shot_id),
    KEY idx_aporia_product_lacuna_expiry (tenant_id, status, expires_at),
    CONSTRAINT chk_aporia_product_lacuna_status CHECK (status IN ('ready','consumed','expired','revoked')),
    CONSTRAINT chk_aporia_product_lacuna_instrument CHECK (instrument IN ('discard_alternative_v1','focus_constraints_v1'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
