CREATE TABLE IF NOT EXISTS `aporia_ecological_relations_r3` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `relation_ref` char(64) NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `relationship_id` bigint unsigned NOT NULL,
  `eligibility_version` varchar(64) NOT NULL,
  `enrolled_at` datetime(6) NOT NULL,
  `baseline_quartile` tinyint unsigned DEFAULT NULL,
  `quartile_model_version` varchar(64) NOT NULL,
  `c0_lineage` char(64) NOT NULL,
  `c5_lineage` char(64) NOT NULL,
  `c0_state_hash` char(64) NOT NULL,
  `c5_state_hash` char(64) NOT NULL,
  `enrollment_status` varchar(48) NOT NULL,
  `provenance_complete` tinyint(1) NOT NULL,
  `censoring_reason` varchar(64) DEFAULT NULL,
  `censored_at` datetime(6) DEFAULT NULL,
  `event_name` varchar(96) NOT NULL,
  `event_version` smallint unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(32) NOT NULL,
  `component` varchar(64) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(32) NOT NULL,
  `target_type` varchar(64) NOT NULL,
  `action_name` varchar(96) NOT NULL,
  `lifecycle_phase` varchar(32) NOT NULL,
  `outcome` varchar(32) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_ecological_r3_relation` (`tenant_id`, `relation_ref`),
  UNIQUE KEY `uniq_aporia_ecological_r3_relationship` (`tenant_id`, `relationship_id`),
  UNIQUE KEY `uniq_aporia_ecological_r3_enrollment_operation` (`tenant_id`, `operation_id`),
  CONSTRAINT `chk_aporia_ecological_r3_quartile` CHECK (`baseline_quartile` IS NULL OR `baseline_quartile` BETWEEN 0 AND 3),
  CONSTRAINT `chk_aporia_ecological_r3_enrollment_audit` CHECK (`event_name` = 'aporia.ecological.relation.enrolled' AND `event_version` = 1 AND `category` = 'audit' AND `component` = 'aporia-ecological-prospective')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_ecological_predictions_r3` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `relation_ref` char(64) NOT NULL,
  `turn_ref` char(64) NOT NULL,
  `observation_commitment` char(64) NOT NULL,
  `c0_prediction_label` varchar(24) NOT NULL,
  `c0_win_probability` decimal(8,6) NOT NULL,
  `c0_prediction_commitment` char(64) NOT NULL,
  `c5_prediction_label` varchar(24) NOT NULL,
  `c5_win_probability` decimal(8,6) NOT NULL,
  `c5_prediction_commitment` char(64) NOT NULL,
  `prediction_sealed_at` datetime(6) NOT NULL,
  `prediction_seal_hash` char(64) NOT NULL,
  `same_observation` tinyint(1) NOT NULL,
  `separate_stores` tinyint(1) NOT NULL,
  `runtime_influence` tinyint(1) NOT NULL,
  `external_effect` tinyint(1) NOT NULL,
  `contamination_detected` tinyint(1) NOT NULL,
  `event_name` varchar(96) NOT NULL,
  `event_version` smallint unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(32) NOT NULL,
  `component` varchar(64) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(32) NOT NULL,
  `target_type` varchar(64) NOT NULL,
  `action_name` varchar(96) NOT NULL,
  `lifecycle_phase` varchar(32) NOT NULL,
  `outcome` varchar(32) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_ecological_r3_prediction` (`tenant_id`, `relation_ref`),
  UNIQUE KEY `uniq_aporia_ecological_r3_prediction_operation` (`tenant_id`, `operation_id`),
  CONSTRAINT `fk_aporia_ecological_r3_prediction_relation` FOREIGN KEY (`tenant_id`, `relation_ref`) REFERENCES `aporia_ecological_relations_r3` (`tenant_id`, `relation_ref`) ON DELETE RESTRICT,
  CONSTRAINT `chk_aporia_ecological_r3_prediction_safety` CHECK (`same_observation` = 1 AND `separate_stores` = 1 AND `runtime_influence` = 0 AND `external_effect` = 0 AND `contamination_detected` = 0),
  CONSTRAINT `chk_aporia_ecological_r3_prediction_probability` CHECK (`c0_win_probability` BETWEEN 0 AND 1 AND `c5_win_probability` BETWEEN 0 AND 1),
  CONSTRAINT `chk_aporia_ecological_r3_prediction_audit` CHECK (`event_name` = 'aporia.ecological.prediction.sealed' AND `event_version` = 1 AND `category` = 'audit' AND `component` = 'aporia-ecological-prospective')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_ecological_terminal_outcomes_r3` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `relation_ref` char(64) NOT NULL,
  `actual_action_source` varchar(32) NOT NULL,
  `actual_action` varchar(64) NOT NULL,
  `terminal_definition` varchar(64) NOT NULL,
  `terminal_outcome` varchar(24) NOT NULL,
  `outcome_timestamp` datetime(6) NOT NULL,
  `censoring_reason` varchar(64) DEFAULT NULL,
  `outcome_commitment` char(64) NOT NULL,
  `adjudication_blinded_to_arm` tinyint(1) NOT NULL,
  `provenance_complete` tinyint(1) NOT NULL,
  `event_name` varchar(96) NOT NULL,
  `event_version` smallint unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(32) NOT NULL,
  `component` varchar(64) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(32) NOT NULL,
  `target_type` varchar(64) NOT NULL,
  `action_name` varchar(96) NOT NULL,
  `lifecycle_phase` varchar(32) NOT NULL,
  `outcome` varchar(32) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_ecological_r3_outcome` (`tenant_id`, `relation_ref`),
  UNIQUE KEY `uniq_aporia_ecological_r3_outcome_operation` (`tenant_id`, `operation_id`),
  CONSTRAINT `fk_aporia_ecological_r3_outcome_relation` FOREIGN KEY (`tenant_id`, `relation_ref`) REFERENCES `aporia_ecological_relations_r3` (`tenant_id`, `relation_ref`) ON DELETE RESTRICT,
  CONSTRAINT `chk_aporia_ecological_r3_outcome_contract` CHECK (`terminal_outcome` IN ('won','lost') AND `adjudication_blinded_to_arm` = 1 AND `provenance_complete` = 1),
  CONSTRAINT `chk_aporia_ecological_r3_outcome_audit` CHECK (`event_name` = 'aporia.ecological.outcome.adjudicated' AND `event_version` = 1 AND `category` = 'audit' AND `component` = 'aporia-ecological-prospective')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_ecological_population_weights_r3` (
  `tenant_id` bigint unsigned NOT NULL,
  `weight_version` varchar(64) NOT NULL,
  `weights_json` varchar(255) NOT NULL,
  `loss_margin` decimal(8,6) NOT NULL,
  `design_commitment` char(64) NOT NULL,
  `frozen_at` datetime(6) NOT NULL,
  PRIMARY KEY (`tenant_id`),
  UNIQUE KEY `uniq_aporia_ecological_r3_design_commitment` (`tenant_id`, `design_commitment`),
  CONSTRAINT `chk_aporia_ecological_r3_loss_margin` CHECK (`loss_margin` > 0 AND `loss_margin` < 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `aporia_ecological_population_weights_r3`
  (`tenant_id`, `weight_version`, `weights_json`, `loss_margin`, `design_commitment`, `frozen_at`)
VALUES
  (49, 'target-balanced-v1', '[0.25,0.25,0.25,0.25]', 0.100000, '8134ff93524a882bd5ab8881227613eb3e0145086707579e938bcdb8304f4455', CURRENT_TIMESTAMP(6))
ON DUPLICATE KEY UPDATE
  `loss_margin` = IF(`design_commitment` = VALUES(`design_commitment`), `loss_margin`, 0);
