CREATE TABLE IF NOT EXISTS `aporia_perspective_observations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `observation_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `event_id` bigint unsigned NOT NULL,
  `perspective` varchar(48) NOT NULL,
  `subject_ref` char(64) NOT NULL,
  `epistemic_status` varchar(24) NOT NULL,
  `confidence` decimal(6,5) DEFAULT NULL,
  `uncertainty_codes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`uncertainty_codes_json`)),
  `evidence_event_ids_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`evidence_event_ids_json`)),
  `value_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`value_json`)),
  `projection_version` int unsigned NOT NULL,
  `adapter_version` int unsigned NOT NULL,
  `policy_hash` char(64) NOT NULL,
  `input_event_set_hash` char(64) NOT NULL,
  `produced_at` datetime(6) NOT NULL,
  `valid_until` datetime(6) DEFAULT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_perspective_observation` (`observation_id`),
  UNIQUE KEY `uniq_aporia_perspective_input` (`tenant_id`, `event_id`, `perspective`, `projection_version`),
  KEY `idx_aporia_perspective_subject` (`tenant_id`, `perspective`, `subject_ref`, `produced_at`, `id`),
  CONSTRAINT `fk_aporia_perspective_event` FOREIGN KEY (`tenant_id`, `event_id`) REFERENCES `aporia_events` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_perspective_status` CHECK (`epistemic_status` IN ('observed','inferred','unknown','conflicted','invalidated')),
  CONSTRAINT `chk_aporia_perspective_confidence` CHECK (`confidence` IS NULL OR (`confidence` >= 0 AND `confidence` <= 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_shadow_envelopes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `envelope_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `event_id` bigint unsigned NOT NULL,
  `session_ref` char(64) NOT NULL,
  `task_ref` char(64) DEFAULT NULL,
  `delivery_mode` varchar(24) NOT NULL DEFAULT 'shadow',
  `observation_ids_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`observation_ids_json`)),
  `event_count` int unsigned NOT NULL,
  `omitted_event_count` int unsigned NOT NULL,
  `completeness` varchar(24) NOT NULL,
  `source_hlc_wall_us` bigint unsigned NOT NULL,
  `source_hlc_logical` int unsigned NOT NULL,
  `prohibitions_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`prohibitions_json`)),
  `policy_hash` char(64) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_shadow_envelope` (`envelope_id`),
  UNIQUE KEY `uniq_aporia_shadow_event` (`tenant_id`, `event_id`),
  KEY `idx_aporia_shadow_task` (`tenant_id`, `task_ref`, `created_at`, `id`),
  CONSTRAINT `fk_aporia_shadow_event` FOREIGN KEY (`tenant_id`, `event_id`) REFERENCES `aporia_events` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_shadow_delivery` CHECK (`delivery_mode` = 'shadow'),
  CONSTRAINT `chk_aporia_shadow_completeness` CHECK (`completeness` IN ('complete','partial'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
