CREATE TABLE IF NOT EXISTS `aporia_shadow_episode_lifecycle` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `session_public_id` char(36) NOT NULL,
  `turn_id` varchar(191) NOT NULL,
  `turn_ref` char(64) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `status` varchar(32) NOT NULL,
  `assigned_at` datetime(6) DEFAULT NULL,
  `preparing_at` datetime(6) DEFAULT NULL,
  `prepared_at` datetime(6) DEFAULT NULL,
  `exposed_at` datetime(6) DEFAULT NULL,
  `c0_prediction_sealed_at` datetime(6) DEFAULT NULL,
  `c5_prediction_sealed_at` datetime(6) DEFAULT NULL,
  `turn_done_at` datetime(6) DEFAULT NULL,
  `usage_terminal_at` datetime(6) DEFAULT NULL,
  `outcome_terminal_at` datetime(6) DEFAULT NULL,
  `outcome_commitment` char(64) DEFAULT NULL,
  `archived_at` datetime(6) DEFAULT NULL,
  `revoked_at` datetime(6) DEFAULT NULL,
  `timed_out_at` datetime(6) DEFAULT NULL,
  `missing_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (`missing_json` IS NULL OR json_valid(`missing_json`)),
  `runtime_influence` tinyint(1) NOT NULL DEFAULT 0,
  `external_effect` tinyint(1) NOT NULL DEFAULT 0,
  `contamination_detected` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_shadow_lifecycle_turn` (`tenant_id`, `turn_ref`),
  UNIQUE KEY `uniq_aporia_shadow_lifecycle_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_shadow_lifecycle_session` (`tenant_id`, `session_public_id`, `status`),
  CONSTRAINT `chk_aporia_shadow_lifecycle_scope` CHECK (`runtime_influence` = 0 AND `external_effect` = 0 AND `contamination_detected` = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_shadow_lifecycle_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `event_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `turn_ref` char(64) NOT NULL,
  `transition_name` varchar(32) NOT NULL,
  `arm` varchar(4) DEFAULT NULL,
  `payload_commitment` char(64) DEFAULT NULL,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `target_type` varchar(40) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `state_before` varchar(32) NOT NULL,
  `state_after` varchar(32) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_shadow_lifecycle_event` (`tenant_id`, `event_id`),
  UNIQUE KEY `uniq_aporia_shadow_lifecycle_transition` (`tenant_id`, `turn_ref`, `transition_name`, `arm`),
  KEY `idx_aporia_shadow_lifecycle_operation` (`tenant_id`, `operation_id`, `created_at`),
  CONSTRAINT `chk_aporia_shadow_lifecycle_event_contract` CHECK (`event_version` = 1 AND `category` = 'audit' AND `component` = 'aporia-shadow-lifecycle' AND `target_type` = 'shadow_episode' AND ((`lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded') OR (`lifecycle_phase` = 'rejected' AND `outcome` = 'denied')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
