CREATE TABLE IF NOT EXISTS `aporia_empirical_corrections` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `correction_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `run_id` char(36) NOT NULL,
  `operator_user_id` bigint NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `previous_evaluations_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`previous_evaluations_json`)),
  `corrected_evaluations_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`corrected_evaluations_json`)),
  `previous_evaluations_commitment` char(64) NOT NULL,
  `corrected_evaluations_commitment` char(64) NOT NULL,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_empirical_correction` (`tenant_id`, `correction_id`),
  UNIQUE KEY `uniq_aporia_empirical_correction_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_empirical_correction_run` (`tenant_id`, `run_id`, `id`),
  CONSTRAINT `fk_aporia_empirical_correction_run` FOREIGN KEY (`tenant_id`, `run_id`) REFERENCES `aporia_empirical_runs` (`tenant_id`, `run_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_empirical_correction_reason` CHECK (`reason_code` = 'bootstrap_sampler_invalid_v1'),
  CONSTRAINT `chk_aporia_empirical_correction_json` CHECK (json_type(`previous_evaluations_json`) = 'ARRAY' AND json_type(`corrected_evaluations_json`) = 'ARRAY'),
  CONSTRAINT `chk_aporia_empirical_correction_audit` CHECK (`event_name` = 'aporia.experiment.empirical.corrected' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-empirical-study' AND `actor_type` = 'admin' AND `action_name` = 'correct_empirical_evaluation' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
