CREATE TABLE IF NOT EXISTS `aporia_ecological_transport_preconditions_r1` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `event_id` char(64) NOT NULL,
  `tenant_id` bigint unsigned NOT NULL,
  `session_ref` char(64) NOT NULL,
  `turn_ref` char(64) NOT NULL,
  `request_ref` char(64) NOT NULL,
  `authenticated_websocket` tinyint(1) NOT NULL,
  `session_turn_binding` tinyint(1) NOT NULL,
  `attested_at` datetime(6) NOT NULL,
  `attestation_hash` char(64) NOT NULL,
  `event_name` varchar(96) NOT NULL,
  `event_version` smallint unsigned NOT NULL,
  `occurred_at` datetime(6) NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(32) NOT NULL,
  `component` varchar(64) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(32) NOT NULL,
  `initiator_type` varchar(32) NOT NULL,
  `executor_type` varchar(32) NOT NULL,
  `source_channel` varchar(32) NOT NULL,
  `target_type` varchar(64) NOT NULL,
  `action_name` varchar(96) NOT NULL,
  `lifecycle_phase` varchar(32) NOT NULL,
  `outcome` varchar(32) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_ecological_transport_event` (`event_id`),
  UNIQUE KEY `uniq_aporia_ecological_transport_turn` (`tenant_id`, `turn_ref`),
  UNIQUE KEY `uniq_aporia_ecological_transport_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_ecological_transport_session` (`tenant_id`, `session_ref`, `attested_at`),
  CONSTRAINT `chk_aporia_ecological_transport_verified` CHECK (`authenticated_websocket` = 1 AND `session_turn_binding` = 1),
  CONSTRAINT `chk_aporia_ecological_transport_audit` CHECK (`event_name` = 'aporia.ecological.transport.verified' AND `event_version` = 1 AND `category` = 'audit' AND `component` = 'aporia-ecological-prospective')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `aporia_ecological_predictions_r3`
  ADD COLUMN IF NOT EXISTS `transport_attestation_hash` char(64) DEFAULT NULL AFTER `prediction_seal_hash`,
  ADD INDEX IF NOT EXISTS `idx_aporia_ecological_r3_transport_attestation` (`tenant_id`, `transport_attestation_hash`);
