ALTER TABLE `aporia_autobiography_entries`
  DROP CONSTRAINT `chk_aporia_autobiography_kind`,
  DROP CONSTRAINT `chk_aporia_autobiography_evaluability`,
  DROP CONSTRAINT `chk_aporia_autobiography_empty_distinctions`,
  DROP CONSTRAINT `chk_aporia_autobiography_empty_futures`,
  DROP CONSTRAINT `chk_aporia_autobiography_audit`;

ALTER TABLE `aporia_autobiography_entries`
  ADD CONSTRAINT `chk_aporia_autobiography_kind` CHECK (`entry_kind` IN ('mechanism_only','negative_observation')),
  ADD CONSTRAINT `chk_aporia_autobiography_evaluability` CHECK ((`entry_kind` = 'mechanism_only' AND `evaluability` = 'not_evaluable') OR (`entry_kind` = 'negative_observation' AND `evaluability` = 'observed')),
  ADD CONSTRAINT `chk_aporia_autobiography_distinctions` CHECK (json_type(`lost_distinction_hashes_json`) = 'ARRAY' AND (`evaluability` = 'observed' OR json_length(`lost_distinction_hashes_json`) = 0)),
  ADD CONSTRAINT `chk_aporia_autobiography_futures` CHECK (json_type(`excluded_future_hashes_json`) = 'ARRAY' AND (`evaluability` = 'observed' OR json_length(`excluded_future_hashes_json`) = 0)),
  ADD CONSTRAINT `chk_aporia_autobiography_audit` CHECK (`event_name` = 'aporia.autobiography.entry.recorded' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-autobiography-ledger' AND `actor_type` = 'worker' AND `action_name` IN ('record_mechanism_only','record_negative_observation') AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded' AND ((`action_name` = 'record_mechanism_only' AND `reason_code` = 'negative_autobiography_not_instrumented') OR (`action_name` = 'record_negative_observation' AND `reason_code` = 'negative_autobiography_observed')));

CREATE TABLE IF NOT EXISTS `aporia_ontology_clusters` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `cluster_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `cluster_key` char(64) NOT NULL,
  `status` varchar(24) NOT NULL,
  `train_count` int unsigned NOT NULL DEFAULT 0,
  `holdout_count` int unsigned NOT NULL DEFAULT 0,
  `distinct_episode_count` int unsigned NOT NULL DEFAULT 0,
  `last_evaluated_train_count` int unsigned NOT NULL DEFAULT 0,
  `last_evaluated_holdout_count` int unsigned NOT NULL DEFAULT 0,
  `proposed_version_id` char(36) DEFAULT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_ontology_cluster` (`tenant_id`, `cluster_id`),
  UNIQUE KEY `uniq_aporia_ontology_cluster_key` (`tenant_id`, `cluster_key`),
  KEY `idx_aporia_ontology_cluster_status` (`tenant_id`, `status`, `updated_at`),
  CONSTRAINT `fk_aporia_ontology_cluster_version` FOREIGN KEY (`tenant_id`, `proposed_version_id`) REFERENCES `aporia_ontology_versions` (`tenant_id`, `version_id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_aporia_ontology_cluster_status` CHECK (`status` IN ('collecting','proposed','shadow','rejected','rolled_back')),
  CONSTRAINT `chk_aporia_ontology_cluster_counts` CHECK (`distinct_episode_count` >= `train_count` AND `distinct_episode_count` >= `holdout_count` AND `distinct_episode_count` = `train_count` + `holdout_count`),
  CONSTRAINT `chk_aporia_ontology_cluster_evaluation_counts` CHECK (`train_count` >= `last_evaluated_train_count` AND `holdout_count` >= `last_evaluated_holdout_count`),
  CONSTRAINT `chk_aporia_ontology_cluster_version_state` CHECK ((`status` = 'collecting' AND `proposed_version_id` IS NULL) OR (`status` IN ('proposed','shadow','rejected','rolled_back') AND `proposed_version_id` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_ontology_residuals` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `residual_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `run_id` bigint unsigned NOT NULL,
  `episode_ref` char(64) NOT NULL,
  `cluster_key` char(64) NOT NULL,
  `dataset_split` varchar(16) NOT NULL,
  `residual_vector_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`residual_vector_json`)),
  `residual_commitment` char(64) NOT NULL,
  `baseline_loss` decimal(20,12) NOT NULL,
  `nearest_similarity` decimal(20,12) NOT NULL,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_ontology_residual` (`tenant_id`, `residual_id`),
  UNIQUE KEY `uniq_aporia_ontology_residual_run` (`tenant_id`, `run_id`),
  UNIQUE KEY `uniq_aporia_ontology_residual_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_ontology_residual_cluster` (`tenant_id`, `cluster_key`, `dataset_split`, `episode_ref`, `id`),
  CONSTRAINT `fk_aporia_ontology_residual_run` FOREIGN KEY (`tenant_id`, `run_id`) REFERENCES `aporia_lacuna_runs` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `fk_aporia_ontology_residual_cluster` FOREIGN KEY (`tenant_id`, `cluster_key`) REFERENCES `aporia_ontology_clusters` (`tenant_id`, `cluster_key`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_ontology_residual_split` CHECK (`dataset_split` IN ('train','holdout')),
  CONSTRAINT `chk_aporia_ontology_residual_vector` CHECK (json_type(`residual_vector_json`) = 'ARRAY' AND json_length(`residual_vector_json`) = 12),
  CONSTRAINT `chk_aporia_ontology_residual_metrics` CHECK (`baseline_loss` >= 0.000000000000 AND `nearest_similarity` >= 0.000000000000 AND `nearest_similarity` <= 1.000000000000),
  CONSTRAINT `chk_aporia_ontology_residual_audit` CHECK (`event_name` = 'aporia.ontology.residual.observed' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-ontology-residual-collector' AND `actor_type` = 'worker' AND `action_name` = 'record_ontology_residual' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded' AND `reason_code` IN ('ontology_inadequacy_candidate_observed','ontology_representation_adequate'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
