CREATE TABLE IF NOT EXISTS `aporia_negative_autobiography_evaluations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `evaluation_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `autobiography_entry_id` char(36) NOT NULL,
  `causal_event_id` char(36) NOT NULL,
  `evaluability` varchar(24) NOT NULL,
  `lost_distinction_hashes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`lost_distinction_hashes_json`)),
  `excluded_future_hashes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`excluded_future_hashes_json`)),
  `distinction_loss_rate` decimal(20,12) DEFAULT NULL,
  `future_exclusion_rate` decimal(20,12) DEFAULT NULL,
  `irrecoverability` decimal(20,12) DEFAULT NULL,
  `causal_efficacy` decimal(20,12) DEFAULT NULL,
  `confidence` decimal(20,12) DEFAULT NULL,
  `reason_codes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`reason_codes_json`)),
  `delta_high` decimal(20,12) NOT NULL,
  `delta_low` decimal(20,12) NOT NULL,
  `payload_hash` char(64) NOT NULL,
  `evaluation_signature` char(64) NOT NULL,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_negative_evaluation` (`tenant_id`, `evaluation_id`),
  UNIQUE KEY `uniq_aporia_negative_entry` (`tenant_id`, `autobiography_entry_id`),
  UNIQUE KEY `uniq_aporia_negative_operation` (`tenant_id`, `operation_id`),
  CONSTRAINT `fk_aporia_negative_entry` FOREIGN KEY (`tenant_id`, `autobiography_entry_id`) REFERENCES `aporia_autobiography_entries` (`tenant_id`, `entry_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_negative_evaluability` CHECK (`evaluability` IN ('observed','not_evaluable')),
  CONSTRAINT `chk_aporia_negative_hash_arrays` CHECK (json_type(`lost_distinction_hashes_json`) = 'ARRAY' AND json_type(`excluded_future_hashes_json`) = 'ARRAY'),
  CONSTRAINT `chk_aporia_negative_evaluation_shape` CHECK ((`evaluability` = 'not_evaluable' AND json_length(`lost_distinction_hashes_json`) = 0 AND json_length(`excluded_future_hashes_json`) = 0 AND `distinction_loss_rate` IS NULL AND `future_exclusion_rate` IS NULL AND `reason_code` = 'hypotheses_and_futures_not_instrumented') OR (`evaluability` = 'observed' AND (`distinction_loss_rate` IS NULL OR (`distinction_loss_rate` >= 0.000000000000 AND `distinction_loss_rate` <= 1.000000000000)) AND (`future_exclusion_rate` IS NULL OR (`future_exclusion_rate` >= 0.000000000000 AND `future_exclusion_rate` <= 1.000000000000)) AND `reason_code` = 'separability_and_future_exclusion_observed')),
  CONSTRAINT `chk_aporia_negative_non_claims` CHECK (`irrecoverability` IS NULL AND `causal_efficacy` IS NULL AND `confidence` IS NULL),
  CONSTRAINT `chk_aporia_negative_thresholds` CHECK (`delta_high` = 0.500000000000 AND `delta_low` = 0.150000000000),
  CONSTRAINT `chk_aporia_negative_audit` CHECK (`event_name` = 'aporia.autobiography.negative_evaluation.recorded' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-negative-autobiography-ledger' AND `actor_type` = 'worker' AND `action_name` = 'record_negative_evaluation' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_identity_heads` (
  `tenant_id` bigint NOT NULL,
  `last_signature` char(64) NOT NULL,
  `snapshot_count` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`tenant_id`),
  CONSTRAINT `chk_aporia_identity_head_signature` CHECK (`last_signature` REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_identity_snapshots` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `snapshot_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `autobiography_entry_id` char(36) NOT NULL,
  `graph_commitments_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`graph_commitments_json`)),
  `behavior_commitments_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`behavior_commitments_json`)),
  `commitment_commitments_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`commitment_commitments_json`)),
  `autobiography_commitments_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`autobiography_commitments_json`)),
  `ontology_commitments_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`ontology_commitments_json`)),
  `graph_root` char(64) NOT NULL,
  `behavior_root` char(64) NOT NULL,
  `commitment_root` char(64) NOT NULL,
  `autobiography_root` char(64) NOT NULL,
  `ontology_root` char(64) NOT NULL,
  `graph_count` bigint unsigned NOT NULL,
  `behavior_count` bigint unsigned NOT NULL,
  `commitment_count` bigint unsigned NOT NULL,
  `autobiography_count` bigint unsigned NOT NULL,
  `ontology_count` bigint unsigned NOT NULL,
  `fingerprint` char(64) NOT NULL,
  `continuity_score` decimal(20,12) NOT NULL,
  `model_dependency` varchar(24) NOT NULL,
  `previous_signature` char(64) NOT NULL,
  `snapshot_signature` char(64) NOT NULL,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) DEFAULT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_identity_snapshot` (`tenant_id`, `snapshot_id`),
  UNIQUE KEY `uniq_aporia_identity_entry` (`tenant_id`, `autobiography_entry_id`),
  UNIQUE KEY `uniq_aporia_identity_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_identity_chain` (`tenant_id`, `id`),
  CONSTRAINT `fk_aporia_identity_entry` FOREIGN KEY (`tenant_id`, `autobiography_entry_id`) REFERENCES `aporia_autobiography_entries` (`tenant_id`, `entry_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_identity_arrays` CHECK (json_type(`graph_commitments_json`) = 'ARRAY' AND json_type(`behavior_commitments_json`) = 'ARRAY' AND json_type(`commitment_commitments_json`) = 'ARRAY' AND json_type(`autobiography_commitments_json`) = 'ARRAY' AND json_type(`ontology_commitments_json`) = 'ARRAY'),
  CONSTRAINT `chk_aporia_identity_score` CHECK (`continuity_score` >= 0.000000000000 AND `continuity_score` <= 1.000000000000),
  CONSTRAINT `chk_aporia_identity_model` CHECK (`model_dependency` = 'none'),
  CONSTRAINT `chk_aporia_identity_audit` CHECK (`event_name` = 'aporia.identity.snapshot.recorded' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-identity-ledger' AND `actor_type` = 'worker' AND `action_name` = 'record_identity_snapshot' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_identity_commitments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `commitment_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `commitment_key` char(64) NOT NULL,
  `commitment_kind` varchar(48) NOT NULL,
  `status` varchar(24) NOT NULL,
  `evidence_count` int unsigned NOT NULL DEFAULT 0,
  `first_causal_event_id` char(36) NOT NULL,
  `last_causal_event_id` char(36) NOT NULL,
  `committed_at` datetime(6) DEFAULT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_identity_commitment` (`tenant_id`, `commitment_id`),
  UNIQUE KEY `uniq_aporia_identity_commitment_key` (`tenant_id`, `commitment_key`),
  UNIQUE KEY `uniq_aporia_identity_commitment_tenant_id` (`tenant_id`, `id`),
  CONSTRAINT `chk_aporia_identity_commitment_kind` CHECK (`commitment_kind` = 'shadow_policy_continuity'),
  CONSTRAINT `chk_aporia_identity_commitment_status` CHECK (`status` IN ('proposed','committed')),
  CONSTRAINT `chk_aporia_identity_commitment_slow` CHECK ((`status` = 'proposed' AND `evidence_count` < 3 AND `committed_at` IS NULL) OR (`status` = 'committed' AND `evidence_count` >= 3 AND `committed_at` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_identity_commitment_evidence` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `evidence_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `commitment_id` bigint unsigned NOT NULL,
  `autobiography_entry_id` char(36) NOT NULL,
  `causal_event_id` char(36) NOT NULL,
  `evidence_ordinal` int unsigned NOT NULL,
  `resulting_status` varchar(24) NOT NULL,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_identity_evidence` (`tenant_id`, `evidence_id`),
  UNIQUE KEY `uniq_aporia_identity_entry_evidence` (`tenant_id`, `commitment_id`, `autobiography_entry_id`),
  UNIQUE KEY `uniq_aporia_identity_evidence_operation` (`tenant_id`, `operation_id`),
  CONSTRAINT `fk_aporia_identity_evidence_commitment` FOREIGN KEY (`tenant_id`, `commitment_id`) REFERENCES `aporia_identity_commitments` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `fk_aporia_identity_evidence_entry` FOREIGN KEY (`tenant_id`, `autobiography_entry_id`) REFERENCES `aporia_autobiography_entries` (`tenant_id`, `entry_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_identity_evidence_status` CHECK (`resulting_status` IN ('proposed','committed')),
  CONSTRAINT `chk_aporia_identity_evidence_audit` CHECK (`event_name` = 'aporia.identity.commitment.evidence_recorded' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-identity-ledger' AND `actor_type` = 'worker' AND `action_name` = 'accumulate_slow_commitment' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
