CREATE TABLE IF NOT EXISTS `aporia_ontology_heads` (
  `tenant_id` bigint NOT NULL,
  `current_version_id` char(36) DEFAULT NULL,
  `version_count` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_ontology_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `version_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `version_number` bigint unsigned NOT NULL,
  `parent_version_id` char(36) DEFAULT NULL,
  `status` varchar(24) NOT NULL,
  `version_commitment` char(64) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_ontology_version` (`tenant_id`, `version_id`),
  UNIQUE KEY `uniq_aporia_ontology_version_number` (`tenant_id`, `version_number`),
  KEY `idx_aporia_ontology_version_status` (`tenant_id`, `status`, `version_number`),
  CONSTRAINT `fk_aporia_ontology_parent` FOREIGN KEY (`tenant_id`, `parent_version_id`) REFERENCES `aporia_ontology_versions` (`tenant_id`, `version_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_ontology_version_status` CHECK (`status` IN ('proposed','shadow','validated','active','deprecated','rejected','rolled_back'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_ontology_primitives` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `primitive_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `version_id` char(36) NOT NULL,
  `definition_commitment` char(64) NOT NULL,
  `positive_example_commitments_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`positive_example_commitments_json`)),
  `negative_example_commitments_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`negative_example_commitments_json`)),
  `vector_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`vector_json`)),
  `state` varchar(24) NOT NULL,
  `duplicate_similarity` decimal(20,12) NOT NULL,
  `mdl_before` decimal(20,12) NOT NULL,
  `mdl_after` decimal(20,12) NOT NULL,
  `mdl_improvement` decimal(20,12) NOT NULL,
  `holdout_improvement` decimal(20,12) NOT NULL,
  `bootstrap_lower_95` decimal(20,12) NOT NULL,
  `topology_before_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`topology_before_json`)),
  `topology_after_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`topology_after_json`)),
  `topology_change` decimal(20,12) DEFAULT NULL,
  `automatic_activation_allowed` tinyint(1) NOT NULL DEFAULT 0,
  `reason_codes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`reason_codes_json`)),
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_ontology_primitive` (`tenant_id`, `primitive_id`),
  UNIQUE KEY `uniq_aporia_ontology_primitive_version` (`tenant_id`, `version_id`),
  UNIQUE KEY `uniq_aporia_ontology_primitive_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_ontology_primitive_state` (`tenant_id`, `state`, `created_at`),
  CONSTRAINT `fk_aporia_ontology_primitive_version` FOREIGN KEY (`tenant_id`, `version_id`) REFERENCES `aporia_ontology_versions` (`tenant_id`, `version_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_ontology_example_arrays` CHECK (json_type(`positive_example_commitments_json`) = 'ARRAY' AND json_length(`positive_example_commitments_json`) > 0 AND json_type(`negative_example_commitments_json`) = 'ARRAY' AND json_length(`negative_example_commitments_json`) > 0),
  CONSTRAINT `chk_aporia_ontology_vector_array` CHECK (json_type(`vector_json`) = 'ARRAY'),
  CONSTRAINT `chk_aporia_ontology_primitive_state` CHECK (`state` IN ('proposed','shadow','validated','active','deprecated','rejected')),
  CONSTRAINT `chk_aporia_ontology_no_auto_activation` CHECK (`automatic_activation_allowed` = 0),
  CONSTRAINT `chk_aporia_ontology_primitive_audit` CHECK (`event_name` = 'aporia.ontology.primitive.evaluated' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-ontology-ledger' AND `actor_type` = 'worker' AND `action_name` = 'evaluate_primitive_proposal' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_ontology_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ontology_event_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `version_id` char(36) NOT NULL,
  `target_version_id` char(36) DEFAULT NULL,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_ontology_event` (`tenant_id`, `ontology_event_id`),
  UNIQUE KEY `uniq_aporia_ontology_event_operation` (`tenant_id`, `operation_id`),
  CONSTRAINT `fk_aporia_ontology_event_version` FOREIGN KEY (`tenant_id`, `version_id`) REFERENCES `aporia_ontology_versions` (`tenant_id`, `version_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_aporia_ontology_event_target` FOREIGN KEY (`tenant_id`, `target_version_id`) REFERENCES `aporia_ontology_versions` (`tenant_id`, `version_id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_aporia_ontology_event_audit` CHECK (`event_name` = 'aporia.ontology.version.rollback.succeeded' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-ontology-ledger' AND `actor_type` = 'worker' AND `action_name` = 'rollback_ontology_version' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded' AND `reason_code` = 'shadow_version_reverted')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
