CREATE TABLE IF NOT EXISTS `aporia_autobiography_heads` (
  `tenant_id` bigint NOT NULL,
  `last_signature` char(64) NOT NULL,
  `entry_count` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`tenant_id`),
  CONSTRAINT `chk_aporia_autobiography_head_signature` CHECK (`last_signature` REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_autobiography_entries` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `entry_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `run_id` bigint unsigned NOT NULL,
  `causal_event_id` char(36) NOT NULL,
  `episode_ref` char(64) NOT NULL,
  `entry_kind` varchar(32) NOT NULL,
  `evaluability` varchar(24) NOT NULL,
  `ontology_before_commitment` char(64) NOT NULL,
  `ontology_after_commitment` char(64) DEFAULT NULL,
  `transformation_commitment` char(64) NOT NULL,
  `lost_distinction_hashes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`lost_distinction_hashes_json`)),
  `excluded_future_hashes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`excluded_future_hashes_json`)),
  `required_primitive_ids_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`required_primitive_ids_json`)),
  `commitment_refs_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`commitment_refs_json`)),
  `outcome_refs_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`outcome_refs_json`)),
  `irrecoverability` decimal(20,12) DEFAULT NULL,
  `causal_efficacy` decimal(20,12) DEFAULT NULL,
  `autobiographic_time` bigint unsigned DEFAULT NULL,
  `confidence` decimal(20,12) DEFAULT NULL,
  `reason_codes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`reason_codes_json`)),
  `policy_hash` char(64) NOT NULL,
  `payload_hash` char(64) NOT NULL,
  `previous_signature` char(64) NOT NULL,
  `entry_signature` char(64) NOT NULL,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) DEFAULT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_autobiography_entry` (`tenant_id`, `entry_id`),
  UNIQUE KEY `uniq_aporia_autobiography_run` (`tenant_id`, `run_id`),
  UNIQUE KEY `uniq_aporia_autobiography_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_autobiography_chain` (`tenant_id`, `id`),
  CONSTRAINT `fk_aporia_autobiography_run` FOREIGN KEY (`tenant_id`, `run_id`) REFERENCES `aporia_lacuna_runs` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_autobiography_kind` CHECK (`entry_kind` = 'mechanism_only'),
  CONSTRAINT `chk_aporia_autobiography_evaluability` CHECK (`evaluability` = 'not_evaluable'),
  CONSTRAINT `chk_aporia_autobiography_non_claims` CHECK (`ontology_after_commitment` IS NULL AND `irrecoverability` IS NULL AND `causal_efficacy` IS NULL AND `autobiographic_time` IS NULL AND `confidence` IS NULL),
  CONSTRAINT `chk_aporia_autobiography_empty_distinctions` CHECK (json_type(`lost_distinction_hashes_json`) = 'ARRAY' AND json_length(`lost_distinction_hashes_json`) = 0),
  CONSTRAINT `chk_aporia_autobiography_empty_futures` CHECK (json_type(`excluded_future_hashes_json`) = 'ARRAY' AND json_length(`excluded_future_hashes_json`) = 0),
  CONSTRAINT `chk_aporia_autobiography_empty_primitives` CHECK (json_type(`required_primitive_ids_json`) = 'ARRAY' AND json_length(`required_primitive_ids_json`) = 0),
  CONSTRAINT `chk_aporia_autobiography_empty_commitments` CHECK (json_type(`commitment_refs_json`) = 'ARRAY' AND json_length(`commitment_refs_json`) = 0),
  CONSTRAINT `chk_aporia_autobiography_empty_outcomes` CHECK (json_type(`outcome_refs_json`) = 'ARRAY' AND json_length(`outcome_refs_json`) = 0),
  CONSTRAINT `chk_aporia_autobiography_audit` CHECK (`event_name` = 'aporia.autobiography.entry.recorded' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-autobiography-ledger' AND `actor_type` = 'worker' AND `action_name` = 'record_mechanism_only' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded' AND `reason_code` = 'negative_autobiography_not_instrumented'),
  CONSTRAINT `chk_aporia_autobiography_payload_hash` CHECK (`payload_hash` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_aporia_autobiography_previous_signature` CHECK (`previous_signature` REGEXP '^[0-9a-f]{64}$'),
  CONSTRAINT `chk_aporia_autobiography_entry_signature` CHECK (`entry_signature` REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
