CREATE TABLE IF NOT EXISTS `aporia_lacuna_crypto_commits` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint NOT NULL,
  `run_id` bigint unsigned NOT NULL,
  `latent_id` char(36) NOT NULL,
  `instrument` varchar(40) NOT NULL,
  `input_ciphertext` mediumblob NOT NULL,
  `input_nonce` varchar(40) NOT NULL,
  `destroyed_ciphertext` mediumblob NOT NULL,
  `destroyed_nonce` varchar(40) NOT NULL,
  `input_commitment` char(64) NOT NULL,
  `output_commitment` char(64) NOT NULL,
  `capability_hash` char(64) NOT NULL,
  `destruction_receipt` char(64) NOT NULL,
  `execution_status` varchar(24) NOT NULL,
  `process_exit_code` smallint NOT NULL,
  `core_dumps_disabled` tinyint(1) NOT NULL,
  `memory_lock_status` varchar(24) NOT NULL,
  `event_name` varchar(80) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(16) NOT NULL,
  `stream` varchar(16) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(64) NOT NULL,
  `operation_id` char(36) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(40) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) DEFAULT NULL,
  `trace_id` char(64) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_lacuna_crypto_latent` (`latent_id`),
  UNIQUE KEY `uniq_aporia_lacuna_crypto_capability` (`capability_hash`),
  UNIQUE KEY `uniq_aporia_lacuna_crypto_instrument` (`tenant_id`, `run_id`, `instrument`),
  UNIQUE KEY `uniq_aporia_lacuna_crypto_tenant_id` (`tenant_id`, `id`),
  KEY `idx_aporia_lacuna_crypto_tenant_created` (`tenant_id`, `created_at`, `id`),
  CONSTRAINT `fk_aporia_lacuna_crypto_run` FOREIGN KEY (`tenant_id`, `run_id`) REFERENCES `aporia_lacuna_runs` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_lacuna_crypto_instrument` CHECK (`instrument` IN ('q_then_r_v2','r_then_q_v2')),
  CONSTRAINT `chk_aporia_lacuna_crypto_status` CHECK (`execution_status` IN ('consumed','destroyed')),
  CONSTRAINT `chk_aporia_lacuna_crypto_memory` CHECK (`memory_lock_status` IN ('locked','unsupported')),
  CONSTRAINT `chk_aporia_lacuna_crypto_stream` CHECK (`stream` = 'system'),
  CONSTRAINT `chk_aporia_lacuna_crypto_category` CHECK (`category` = 'audit'),
  CONSTRAINT `chk_aporia_lacuna_crypto_actor` CHECK (`actor_type` = 'worker'),
  CONSTRAINT `chk_aporia_lacuna_crypto_lifecycle` CHECK (`lifecycle_phase` = 'succeeded'),
  CONSTRAINT `chk_aporia_lacuna_crypto_outcome` CHECK (`outcome` = 'succeeded'),
  CONSTRAINT `chk_aporia_lacuna_crypto_core` CHECK (`core_dumps_disabled` = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
