CREATE TABLE IF NOT EXISTS `aporia_obstruction_measurements` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `measurement_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `run_id` bigint unsigned NOT NULL,
  `world_score` decimal(20,12) NOT NULL,
  `self_score` decimal(20,12) NOT NULL,
  `corrected_self_score` decimal(20,12) NOT NULL,
  `cycle_score` decimal(20,12) NOT NULL,
  `classification` varchar(40) NOT NULL,
  `satisfiable` tinyint(1) NOT NULL,
  `self_referential` tinyint(1) NOT NULL,
  `unsat_constraint_hashes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`unsat_constraint_hashes_json`)),
  `multi_start_scores_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`multi_start_scores_json`)),
  `reason_codes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`reason_codes_json`)),
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_obstruction_measurement` (`tenant_id`, `measurement_id`),
  UNIQUE KEY `uniq_aporia_obstruction_run` (`tenant_id`, `run_id`),
  UNIQUE KEY `uniq_aporia_obstruction_operation` (`tenant_id`, `operation_id`),
  CONSTRAINT `fk_aporia_obstruction_run` FOREIGN KEY (`tenant_id`, `run_id`) REFERENCES `aporia_lacuna_runs` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_obstruction_scores` CHECK (`world_score` >= 0 AND `self_score` >= 0 AND `corrected_self_score` >= 0 AND `cycle_score` >= 0),
  CONSTRAINT `chk_aporia_obstruction_classification` CHECK (`classification` IN ('globally_consistent','world_conflict','transport_error','self_obstruction_candidate','incomplete_or_unlocalized')),
  CONSTRAINT `chk_aporia_obstruction_arrays` CHECK (json_type(`unsat_constraint_hashes_json`) = 'ARRAY' AND json_type(`multi_start_scores_json`) = 'ARRAY' AND json_type(`reason_codes_json`) = 'ARRAY'),
  CONSTRAINT `chk_aporia_obstruction_audit` CHECK (`event_name` = 'aporia.obstruction.measurement.recorded' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-obstruction-engine' AND `actor_type` = 'worker' AND `action_name` = 'measure_obstruction' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_experiment_preregistrations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `experiment_key` varchar(64) NOT NULL,
  `protocol_commitment` char(64) NOT NULL,
  `arms_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`arms_json`)),
  `hypotheses_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`hypotheses_json`)),
  `metrics_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`metrics_json`)),
  `seeds_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`seeds_json`)),
  `locked_at` datetime(6) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_experiment_preregistration` (`experiment_key`),
  CONSTRAINT `chk_aporia_experiment_preregistration_arrays` CHECK (json_type(`arms_json`) = 'ARRAY' AND json_type(`hypotheses_json`) = 'ARRAY' AND json_type(`metrics_json`) = 'ARRAY' AND json_type(`seeds_json`) = 'ARRAY')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_experiment_assignments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `assignment_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `episode_ref` char(64) NOT NULL,
  `experiment_key` varchar(64) NOT NULL,
  `arm` char(2) NOT NULL,
  `seed` bigint unsigned NOT NULL,
  `assignment_commitment` char(64) NOT NULL,
  `assigned_before_outcome` tinyint(1) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_experiment_assignment` (`tenant_id`, `assignment_id`),
  UNIQUE KEY `uniq_aporia_experiment_episode` (`tenant_id`, `episode_ref`, `experiment_key`),
  KEY `idx_aporia_experiment_arm` (`experiment_key`, `arm`, `created_at`, `id`),
  CONSTRAINT `fk_aporia_experiment_protocol` FOREIGN KEY (`experiment_key`) REFERENCES `aporia_experiment_preregistrations` (`experiment_key`) ON DELETE RESTRICT,
  CONSTRAINT `chk_aporia_experiment_arm` CHECK (`arm` IN ('C0','C1','C2','C3','C4','C5')),
  CONSTRAINT `chk_aporia_experiment_assignment_timing` CHECK (`assigned_before_outcome` = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_experiment_outcomes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `outcome_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `assignment_id` char(36) NOT NULL,
  `run_id` bigint unsigned NOT NULL,
  `metric_name` varchar(64) NOT NULL,
  `numeric_value` decimal(20,12) NOT NULL,
  `favorable_direction` varchar(16) NOT NULL,
  `reason_codes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`reason_codes_json`)),
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_experiment_outcome` (`tenant_id`, `outcome_id`),
  UNIQUE KEY `uniq_aporia_experiment_run_metric` (`tenant_id`, `run_id`, `metric_name`),
  CONSTRAINT `fk_aporia_experiment_outcome_assignment` FOREIGN KEY (`tenant_id`, `assignment_id`) REFERENCES `aporia_experiment_assignments` (`tenant_id`, `assignment_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_aporia_experiment_outcome_run` FOREIGN KEY (`tenant_id`, `run_id`) REFERENCES `aporia_lacuna_runs` (`tenant_id`, `id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_experiment_metric` CHECK (`metric_name` IN ('path_dependence','identity_continuity','world_obstruction','self_obstruction','incorrect_effect_rate','false_block_rate','factual_consistency','latency_ms','cost_units')),
  CONSTRAINT `chk_aporia_experiment_direction` CHECK (`favorable_direction` IN ('higher','lower'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_hirt_decisions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `decision_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `episode_ref` char(64) NOT NULL,
  `action_commitment` char(64) NOT NULL,
  `mode` varchar(24) NOT NULL,
  `effect_commitment` char(64) NOT NULL,
  `meet_commitment` char(64) NOT NULL,
  `decision` varchar(32) NOT NULL,
  `allowed` tinyint(1) NOT NULL,
  `reversible` tinyint(1) NOT NULL,
  `external` tinyint(1) NOT NULL,
  `risk` decimal(6,5) NOT NULL,
  `safe_prefix_count` int unsigned NOT NULL,
  `reason_codes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`reason_codes_json`)),
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_hirt_decision` (`tenant_id`, `decision_id`),
  UNIQUE KEY `uniq_aporia_hirt_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_hirt_episode` (`tenant_id`, `episode_ref`, `created_at`, `id`),
  CONSTRAINT `chk_aporia_hirt_mode` CHECK (`mode` IN ('shadow','advisory','guarded_reversible')),
  CONSTRAINT `chk_aporia_hirt_decision_state` CHECK (`decision` IN ('shadow_observed','advisory_only','safe_prefix_allowed','blocked','evidence_required','escalation_required')),
  CONSTRAINT `chk_aporia_hirt_risk` CHECK (`risk` >= 0 AND `risk` <= 1),
  CONSTRAINT `chk_aporia_hirt_audit` CHECK (`event_name` = 'aporia.hirt.effect.decision.recorded' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-hirt-gateway' AND `actor_type` = 'worker' AND `action_name` = 'inspect_effect' AND `lifecycle_phase` IN ('succeeded','rejected') AND `outcome` IN ('succeeded','rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_advisory_exposures` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `exposure_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `assignment_id` char(36) NOT NULL,
  `episode_ref` char(64) NOT NULL,
  `delivery` varchar(24) NOT NULL,
  `envelope_commitment` char(64) NOT NULL,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_advisory_exposure` (`tenant_id`, `exposure_id`),
  UNIQUE KEY `uniq_aporia_advisory_episode` (`tenant_id`, `episode_ref`),
  UNIQUE KEY `uniq_aporia_advisory_operation` (`tenant_id`, `operation_id`),
  CONSTRAINT `fk_aporia_advisory_assignment` FOREIGN KEY (`tenant_id`, `assignment_id`) REFERENCES `aporia_experiment_assignments` (`tenant_id`, `assignment_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_advisory_delivery` CHECK (`delivery` IN ('baseline','advisory')),
  CONSTRAINT `chk_aporia_advisory_audit` CHECK (`event_name` = 'aporia.advisory.envelope.delivered' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-advisory-context' AND `actor_type` = 'worker' AND `action_name` = 'deliver_advisory_envelope' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_advisory_outcomes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `advisory_outcome_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `assignment_id` char(36) NOT NULL,
  `episode_ref` char(64) NOT NULL,
  `decision_commitment` char(64) NOT NULL,
  `baseline_decision_commitment` char(64) DEFAULT NULL,
  `decision_changed` tinyint(1) DEFAULT NULL,
  `feedback_correct` tinyint(1) DEFAULT NULL,
  `confidence` decimal(8,7) DEFAULT NULL,
  `brier_score` decimal(20,12) DEFAULT NULL,
  `calibration_error` decimal(20,12) DEFAULT NULL,
  `latency_ms` bigint unsigned NOT NULL,
  `cost_units` decimal(20,6) NOT NULL,
  `critical_regression` tinyint(1) NOT NULL DEFAULT 0,
  `evaluability` varchar(24) NOT NULL,
  `reason_codes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`reason_codes_json`)),
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_advisory_outcome` (`tenant_id`, `advisory_outcome_id`),
  UNIQUE KEY `uniq_aporia_advisory_episode_outcome` (`tenant_id`, `episode_ref`),
  CONSTRAINT `fk_aporia_advisory_outcome_assignment` FOREIGN KEY (`tenant_id`, `assignment_id`) REFERENCES `aporia_experiment_assignments` (`tenant_id`, `assignment_id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_advisory_outcome_scores` CHECK ((`confidence` IS NULL OR (`confidence` >= 0 AND `confidence` <= 1)) AND (`brier_score` IS NULL OR (`brier_score` >= 0 AND `brier_score` <= 1)) AND (`calibration_error` IS NULL OR (`calibration_error` >= 0 AND `calibration_error` <= 1)) AND `cost_units` >= 0),
  CONSTRAINT `chk_aporia_advisory_outcome_eval` CHECK (`evaluability` IN ('observed','not_evaluable')),
  CONSTRAINT `chk_aporia_advisory_outcome_arrays` CHECK (json_type(`reason_codes_json`) = 'ARRAY')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_guarded_policies` (
  `tenant_id` bigint NOT NULL,
  `status` varchar(24) NOT NULL,
  `approval_commitment` char(64) DEFAULT NULL,
  `approved_by_user_id` bigint DEFAULT NULL,
  `risk_threshold` decimal(6,5) NOT NULL DEFAULT 0.25000,
  `daily_call_limit` int unsigned NOT NULL DEFAULT 0,
  `daily_cost_limit` decimal(20,6) NOT NULL DEFAULT 0,
  `kill_switch` tinyint(1) NOT NULL DEFAULT 1,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`tenant_id`),
  CONSTRAINT `chk_aporia_guarded_status` CHECK (`status` IN ('disabled','approved','active','rolled_back')),
  CONSTRAINT `chk_aporia_guarded_approval` CHECK ((`status` = 'disabled' AND `approval_commitment` IS NULL AND `approved_by_user_id` IS NULL AND `kill_switch` = 1) OR (`status` IN ('approved','active','rolled_back') AND `approval_commitment` REGEXP '^[0-9a-f]{64}$' AND `approved_by_user_id` > 0)),
  CONSTRAINT `chk_aporia_guarded_activation` CHECK (`status` <> 'active' OR (`kill_switch` = 0 AND `daily_call_limit` > 0 AND `daily_cost_limit` > 0)),
  CONSTRAINT `chk_aporia_guarded_limits` CHECK (`risk_threshold` >= 0 AND `risk_threshold` <= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_guarded_usage` (
  `tenant_id` bigint NOT NULL,
  `usage_date` date NOT NULL,
  `call_count` int unsigned NOT NULL DEFAULT 0,
  `cost_units` decimal(20,6) NOT NULL DEFAULT 0,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`tenant_id`, `usage_date`),
  CONSTRAINT `chk_aporia_guarded_usage_nonnegative` CHECK (`cost_units` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_guarded_policy_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `policy_event_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `status` varchar(24) NOT NULL,
  `approval_commitment` char(64) DEFAULT NULL,
  `approved_by_user_id` bigint DEFAULT NULL,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `schema_version` int unsigned NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_guarded_policy_event` (`tenant_id`, `policy_event_id`),
  UNIQUE KEY `uniq_aporia_guarded_policy_operation` (`tenant_id`, `operation_id`),
  CONSTRAINT `chk_aporia_guarded_policy_event_status` CHECK (`status` IN ('approved','active','rolled_back')),
  CONSTRAINT `chk_aporia_guarded_policy_event_audit` CHECK (`event_name` = 'aporia.guarded.policy.changed' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-guarded-policy' AND `actor_type` = 'user' AND `action_name` IN ('approve_guarded_policy','activate_guarded_policy','rollback_guarded_policy') AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
