CREATE TABLE IF NOT EXISTS `aporia_ecological_episode_outcomes_r2` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `event_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `relationship_ref` char(64) NOT NULL,
  `relationship_revision` bigint unsigned NOT NULL,
  `turn_ref` char(64) NOT NULL,
  `session_ref` char(64) NOT NULL,
  `c0_observation_commitment` char(64) NOT NULL,
  `c0_prediction_commitment` char(64) NOT NULL,
  `c5_observation_commitment` char(64) NOT NULL,
  `c5_prediction_commitment` char(64) NOT NULL,
  `outcome_label` varchar(16) NOT NULL,
  `outcome_commitment` char(64) NOT NULL,
  `outcome_at` datetime(6) NOT NULL,
  `same_observation` tinyint(1) NOT NULL DEFAULT 1,
  `predictions_before_outcome` tinyint(1) NOT NULL DEFAULT 1,
  `runtime_influence` tinyint(1) NOT NULL DEFAULT 0,
  `external_effect` tinyint(1) NOT NULL DEFAULT 0,
  `contamination_detected` tinyint(1) NOT NULL DEFAULT 0,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `target_type` varchar(40) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_ecological_event` (`tenant_id`, `event_id`),
  UNIQUE KEY `uniq_aporia_ecological_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_ecological_outcome` (`tenant_id`, `outcome_at`, `outcome_label`),
  KEY `idx_aporia_ecological_turn` (`tenant_id`, `turn_ref`, `relationship_revision`),
  CONSTRAINT `fk_aporia_ecological_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_aporia_ecological_label` CHECK (`outcome_label` IN ('won', 'lost')),
  CONSTRAINT `chk_aporia_ecological_scope` CHECK (`same_observation` = 1 AND `predictions_before_outcome` = 1 AND `runtime_influence` = 0 AND `external_effect` = 0 AND `contamination_detected` = 0),
  CONSTRAINT `chk_aporia_ecological_audit` CHECK (`event_name` = 'aporia.ecological.commercial_outcome.recorded' AND `event_version` = 2 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-ecological-shadow' AND `actor_type` = 'system' AND `target_type` = 'shadow_episode' AND `action_name` = 'record_commercial_outcome' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
