CREATE TABLE IF NOT EXISTS `aporia_longitudinal_shadow_c0` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `shadow_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `turn_ref` char(64) NOT NULL,
  `observation_commitment` char(64) NOT NULL,
  `prediction_label` varchar(24) NOT NULL,
  `prediction_commitment` char(64) NOT NULL,
  `outcome_commitment` char(64) DEFAULT NULL,
  `assigned_before_outcome` tinyint(1) NOT NULL DEFAULT 1,
  `runtime_influence` tinyint(1) NOT NULL DEFAULT 0,
  `external_effect` tinyint(1) NOT NULL DEFAULT 0,
  `contamination_detected` tinyint(1) NOT NULL DEFAULT 0,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `outcome_recorded_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_longitudinal_c0_shadow` (`tenant_id`, `shadow_id`),
  UNIQUE KEY `uniq_aporia_longitudinal_c0_turn` (`tenant_id`, `turn_ref`),
  UNIQUE KEY `uniq_aporia_longitudinal_c0_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_longitudinal_c0_outcome` (`tenant_id`, `outcome_recorded_at`),
  CONSTRAINT `chk_aporia_longitudinal_c0_scope` CHECK (`assigned_before_outcome` = 1 AND `runtime_influence` = 0 AND `external_effect` = 0 AND `contamination_detected` = 0),
  CONSTRAINT `chk_aporia_longitudinal_c0_audit` CHECK (`event_name` = 'aporia.longitudinal.shadow.prediction.recorded' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-longitudinal-shadow' AND `actor_type` = 'worker' AND `action_name` = 'record_shadow_prediction' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aporia_longitudinal_shadow_c5` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `shadow_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `turn_ref` char(64) NOT NULL,
  `observation_commitment` char(64) NOT NULL,
  `prediction_label` varchar(24) NOT NULL,
  `prediction_commitment` char(64) NOT NULL,
  `outcome_commitment` char(64) DEFAULT NULL,
  `assigned_before_outcome` tinyint(1) NOT NULL DEFAULT 1,
  `runtime_influence` tinyint(1) NOT NULL DEFAULT 0,
  `external_effect` tinyint(1) NOT NULL DEFAULT 0,
  `contamination_detected` tinyint(1) NOT NULL DEFAULT 0,
  `event_name` varchar(160) NOT NULL,
  `event_version` int unsigned NOT NULL,
  `environment` varchar(24) NOT NULL,
  `stream` varchar(24) NOT NULL,
  `category` varchar(24) NOT NULL,
  `component` varchar(80) NOT NULL,
  `operation_id` char(64) NOT NULL,
  `actor_type` varchar(24) NOT NULL,
  `action_name` varchar(80) NOT NULL,
  `lifecycle_phase` varchar(24) NOT NULL,
  `outcome` varchar(24) NOT NULL,
  `reason_code` varchar(80) NOT NULL,
  `outcome_recorded_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_aporia_longitudinal_c5_shadow` (`tenant_id`, `shadow_id`),
  UNIQUE KEY `uniq_aporia_longitudinal_c5_turn` (`tenant_id`, `turn_ref`),
  UNIQUE KEY `uniq_aporia_longitudinal_c5_operation` (`tenant_id`, `operation_id`),
  KEY `idx_aporia_longitudinal_c5_outcome` (`tenant_id`, `outcome_recorded_at`),
  CONSTRAINT `chk_aporia_longitudinal_c5_scope` CHECK (`assigned_before_outcome` = 1 AND `runtime_influence` = 0 AND `external_effect` = 0 AND `contamination_detected` = 0),
  CONSTRAINT `chk_aporia_longitudinal_c5_audit` CHECK (`event_name` = 'aporia.longitudinal.shadow.prediction.recorded' AND `event_version` = 1 AND `stream` = 'system' AND `category` = 'audit' AND `component` = 'aporia-longitudinal-shadow' AND `actor_type` = 'worker' AND `action_name` = 'record_shadow_prediction' AND `lifecycle_phase` = 'succeeded' AND `outcome` = 'succeeded')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
